### ISSUE TITLE
Path is not used

### ISSUE THREAD

**Issue by assertnotnull** [felixjb/testify#105]
**Describe the bug**
The path is not used when it is set.

**To Reproduce**
In the VScode config, change the extension configuration `testify.testRunnerPath` to `./node_modules/mocha/bin/mocha.js`

It still runs the tests with `node_modules/.bin/mocha`

**Expected behavior**
To run with the said file

**Screenshots/GIFs**
![image](https://user-images.githubusercontent.com/821567/216659689-ba52c406-d080-4c9e-b988-7ec4f4578e26.png)
**Platform:**

ZorinOS 16.2
VSCode@1.74.3

**Test Framework:**
Testify@1.9.0
mocha@10.1.0
PNPM@7.18.2

**Comment by felixjb** [comment]
Hello! 

Is there any reason why using `node_modules/.bin/mocha` is not good enough?

**Comment by felixjb** [comment]
Hello! 

I'm sorry for taking embarrassingly long to respond. I found the issue. 

The problem is the path you used. You need to point the extension to a binary file, not a JavaScript file. If the file is not a valid test runner, the extension uses the default path.

❌  `./node_modules/mocha/bin/mocha.js`
✅ `./node_modules/mocha/bin/_mocha`
